In [2]:
import numpy as np


In [3]:
A=np.array(5)
A

array(5)

In [4]:
np.ndim(A)

0

In [5]:
one=np.array([1,2,3,4,5])
one

array([1, 2, 3, 4, 5])

In [7]:
two=np.array([[1,2,3],[4,5,6]])
two

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
three=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
three

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:

np.ndim(one)
np.ndim(two)
np.ndim(three)

3

In [ ]:
list1=[1,4.0.'apple']
arr=np.array([1,2,3,4,5])


In [3]:

import numpy as np
arr=np.array([1,2,3.4,'apple'])# type conversion
arr

array(['1', '2', '3.4', 'apple'], dtype='<U32')

In [4]:
arr=np.array([1,2,3,4,5])# allow mathematical calculation
arr/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [10]:
# reshaping array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])# 1d array
new_arr=arr.reshape(3,4)

In [11]:
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
# 1D to3D array
new_arr=arr.reshape(2,3,2)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [15]:
print(arr[1]+arr[3])# addition of array element

6


In [17]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,2])
print(arr[1,3])

3
9


In [19]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])
print(arr[1,0,1])

6
8
