In [3]:
# slicing array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
arr
print(arr[1:4])
print(arr[:4])
print(arr[1:])

[2 3 4]
[1 2 3 4]
[2 3 4 5 6 7]


In [5]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2[1,1:4])
print(a2[0:2,2])
print(a2[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [16]:
# append ,insert,delete operation
a=np.array([[1,2,3],[4,5,6]])
# append
#np.append(a,[7,8,9])
#np.append(a,[[7,8,9]],axis=0)
np.append(a,[[5],[8]],axis=1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [25]:
a=np.array([[1,2],[3,4],[5,6]])
#np.insert(a,3,[11,12])
#np.insert(a,1,[11,12],axis=0)
#np.insert(a,1,[11,12,13],axis=1)

# delete method
# np.delete(a,5)
# np.delete(a,1,axis=0)
np.delete(a,1,axis=1)


array([[1],
       [3],
       [5]])

In [31]:
a=np.array([1,2,3])
b=np.array([4,5,6])
# print(a,b)
# print(np.ndim(a),np.ndim(b))
result=np.hstack((a,b))
print(result)
result1=np.vstack((a,b))
print(result1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [36]:
arr1=np.array([[2,4],[6,8]])
arr2=np.array([[3,5],[7,9]])
# new=np.concatenate((arr1,arr2),axis=0)
# print(new)
new=np.concatenate((arr1,arr2),axis=1)
print(new)

[[2 4 3 5]
 [6 8 7 9]]
